### ISSUE TITLE
Confusion on Imports vs Originals

### ISSUE THREAD

**Issue by nik0kin** [photoprism/photoprism-docs#10]
I am confused after reading https://docs.photoprism.org/en/latest/getting-started/docker-compose/

Should I import via putting files in "Import" folder, then running `photoprism import` or by putting files in "Originals" folder and running `photoprism index` ?

The photos are both **Originals** and something I want to **Import**, so what's the difference? Is there another page that explains this?

**Comment by lastzero** [comment]
We know, we need to explain this better. The getting started page was meant as a quick start guide without going into details.

Did you see https://demo.photoprism.org/library/import?

Basically, you can do both. Depends on your use case. When you manage your library manually, we can obviously not filter out duplicates for you to save storage. Also we need to rescan the complete library to detect changes.

When you import, we know exactly what was added and when use file/path names that automatically avoid duplicates.

**Comment by lastzero** [comment]
In fact, you can even mix both ways of adding/indexing photos. Soon, we'll also have symlink support so you can index multiple directories and use import only for uploads or specific / new files.

**Comment by lastzero** [comment]
Added this topic to our [FAQ](http://docs.photoprism.org/getting-started/faq/):

### I'm having issues understanding the difference between the import and originals folders? ###

Import is a temporary folder from which you can move or copy files to originals in a structured way that avoids duplicates. Most users with existing collections will want to index their originals directly without importing them, so that existing file and directory names stay the same. On the other hand, importing is more efficient when adding files as you don't need to re-index all originals to find new photos and videos.

**Comment by spupuz** [comment]
so adding a news photo means resync all???

**Comment by graciousgrey** [comment]
We have a more detailed explanation in our user guide: https://docs.photoprism.org/user-guide/library/import-vs-index/ now.
You do not need to re-index all photos, when adding new ones. Unless the option "complete rescan" is checked only new or changed files from the originals folder are indexed.

**Comment by spupuz** [comment]
> We have a more detailed explanation in our user guide: https://docs.photoprism.org/user-guide/library/import-vs-index/ now.
> You do not need to re-index all photos, when adding new ones. Unless the option "complete rescan" is checked only new or changed files from the originals folder are indexed.

ok thanks for your explaination

**Comment by spupuz** [comment]
if i add a new pic do i have to press rescan or it add it automatically?

**Comment by graciousgrey** [comment]
If you add the image to your originals folder via the filesystem, you need to start the indexer as described here: https://docs.photoprism.org/user-guide/library/indexing/. If "complete rescan" is not selected only the new image will be indexed.

**Comment by bwernerwjw-debug** [comment]
Ever fix this?? links are broken!!

**Comment by photoprismci** [comment]
This issue is from 2020 and was answered at the time — the links are broken because those pages have been reorganized since, not because the content was removed.

Current locations:

- **Import vs. index:** https://docs.photoprism.app/user-guide/library/
- **Indexing originals:** https://docs.photoprism.app/user-guide/library/originals/
- **Importing to originals:** https://docs.photoprism.app/user-guide/library/import/

We have added redirects for the two old URLs in this thread, so they should resolve again once the next docs build is published. Note that the documentation also moved from `docs.photoprism.org` to `docs.photoprism.app`, so very old links may need the newer domain.
