### ISSUE TITLE
Get started page has no link to free version

### ISSUE THREAD

**Issue by niwla23** [photoprism/photoprism-docs#147]
When you come to the photoprism website as a new user and press Get Started you are presented with this:
![image](https://user-images.githubusercontent.com/46248939/215837737-adb32c58-28d0-4d61-81d1-1c7b926b24bc.png)

This looks like there is no free option, even though there is. If you go to the documentation, there are detailed instructions on how to set it up without paying. So why is there no link to a simple installation on the get started page?

**Comment by lastzero** [comment]
@alexislefebvre @niwla23 Be aware that we offer much of our functionality for free because it is a [matter of freedom, not cost](https://en.wikipedia.org/wiki/Gratis_versus_libre). As you noted, this and the membership information are the only pages where we offer paid products and services to fund development. That should be in your own best interest.

Nevertheless, we will continue to improve the information, wording and usability as our time permits. All in all, our website is really good and contains all the information you need if you keep reading. Users can easily find all the free things we offer. Most of them install PhotoPrism through an app store anyway before they even visit our website.

**Comment by alexislefebvre** [comment]
I agree with niwla23 that all options should be equally visible. While I understand that the page emphasize the paid options - since you try to make money from this beautiful project and that's understandable -, in my humble opinion hiding the free option is confusing.

I suggest to merge the 2 options that have the same price, and add a "community - **pay as you want**" option, hopefully it should motivate people to support this project.

And also remove prices per year or price per month, use only one period, not two since it's harder to compare.

**Comment by lastzero** [comment]
We are far away from making money and if we do, it will be spent on expanding our team. Also, we don't have a team working full time on our website. I suggest that now we focus on the next release and multi-user. Would that be acceptable?

**Comment by lastzero** [comment]
Once we have Stripe ready and no longer depend on GitHub Sponsors and Patreon, changes will be much easier to implement. Right now, we don't have full control over pricing and payment intervals. That's the problem.

Of course, you can still criticize the site, but that doesn't help. Ultimately, users also need to understand the difference between gratis and libre. Our solution was never intended to be gratis. Why put this in the focus then and promote it?
