### ISSUE TITLE
Questions about details in Setup documentation

### ISSUE THREAD

**Issue by scotws** [photoprism/photoprism-docs#3]
**As an end-user with some familiarity with Docker, I have some questions regarding the Setup documentation:**

* **Before Step 1**, it says _We plan to ship the final app as a single binary including all dependencies_. This could be understood that the final version will _not_ be available as a Docker container, which sounds unlikely (personally, I'd say "utter madness", but that's just me). Might there be an "as well" missing here?

- In **Step 1**, can the line `-v ~/Pictures:/home/photoprism/Pictures/Originals` have the `:ro` (read-only) parameter added without ill effects? Or will this mean that (say) thumbnails will not be stored once generated?

- In **Updating**, does Photoprism play nice with Watchtower (https://github.com/containrrr/watchtower)? Some of us are too lazy to update their containers by hand.

Possibly missing:

- Photoprism seems to expose **Port 4000 for the database** (if I understand the `docker-compose.yml` correctly). This should probably be documented here, because it conflicts for instance with the Telnet port of Evennia (https://github.com/evennia/evennia). -- It's possible, however, that I've just misunderstood the setup, because the exposure is only in `docker-compose.yml` and not the script presented here. Is 4000 only exposed for testing/development?

Some further questions I don't see covered yet:

- Will the Docker container run on **ARM**? There seems to be no limit to things that people will try to run on their Raspberry Pi.
- Will the container here run with **Podman** (https://podman.io/) as well? Some people don't like the daemon setup of Docker for security reasons.

Thank you!

**Comment by lastzero** [comment]
1. We will always provide a Docker image, but some users asked for a binary because they don't know Docker and don't want to use Docker. However, building a single binary turned out to be more difficult than thought.

2. As mentioned in the related issue, we will not modify any original file. Read-only basically means you can not import, upload, convert or delete. The thumbnail path must be writable. Originals obviously is not for thumbnail.

3. We use Watchtower for our demo, however note that the database is still changed a lot and we can not provide a smooth upgrade path for the multiple changes we do each day. So you have to re-index for now (and delete the old db, which are just files inside the container by default).

4. We don't want to use the same port as mysql, so we've chosen 4000. If that causes issues, what would be a good choice? Also you don't need to expose it, if you don't want to use SQL tools.

5. We work on an ARM image, there is an issue for this in our main repo.

6. I have no experience with Podman, sorry.
