### ISSUE TITLE
Add Patreon to banner?

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism-docs#58]
I see that there's a banner at the top of the docs mentioning GitHub Sponsors. I thought it might be a good idea to add the Patreon link there as well. A decent fraction of users probably are not software developers and wouldn't have Github accounts and so Patreon might be more widely used outside that demographic.

https://github.com/photoprism/photoprism-docs/blob/b5c033ca47989930d06e9729e8f0cd3cd9df386a/overrides/main.html

Also, another idea might be to add a banner or menu item to the navigation in the product. This could be disabled with an option, but appear by default.

**Comment by lastzero** [comment]
True - we actually want to use a Stripe account long-term as Patreon charges lots of fees, just didn't have time to complete the payment flow yet due to complex tax regulations. Turned out this is super difficult in the EU as we need to verify the country for each sponsor and pay VAT to each country separately. Instead of spending time promoting Patreon, we'd rather continue working on Stripe once the most important UX issue are fixed.
